<?php $metaTitle='Learn AI for Law | LexAI Academy'; include __DIR__.'/includes/header.php';
$courses=$db->query("SELECT * FROM courses WHERE status='published' ORDER BY id DESC LIMIT 6")->fetchAll();
$faqs=$db->query('SELECT question,answer FROM faqs WHERE is_active=1 LIMIT 4')->fetchAll();
?>
<header class="hero py-5"><div class="container py-4"><div class="row align-items-center g-4"><div class="col-lg-7">
<span class="badge bg-primary-subtle text-primary mb-3">Premium Legal-Tech Education</span>
<h1>Learn AI for Law. Build the Future of Legal Practice.</h1>
<p class="lead">Structured practical programs for law students, associates, advocates, and legal teams to apply AI safely in research, drafting, summarisation, and productivity workflows.</p>
<div class="d-flex gap-2"><a href="/courses.php" class="btn btn-primary">Explore Courses</a><a href="/login.php" class="btn btn-outline-primary">Student Login</a><a href="/register.php" class="btn btn-dark">Enroll Now</a></div>
<div class="row mt-4 small text-muted"><div class="col-6 col-md-4">✓ Live + Recorded Learning</div><div class="col-6 col-md-4">✓ Practical Legal Use Cases</div><div class="col-6 col-md-4">✓ Certificate on Completion</div></div>
</div><div class="col-lg-5"><div class="card shadow-sm"><div class="card-body"><h5>Why AI Skills Matter in Law</h5><p>Modern legal careers now require fluency in AI-assisted research, prompt drafting, contract review support, and responsible AI governance.</p></div></div></div></div></div></header>
<section class="py-4 bg-light border-top border-bottom"><div class="container d-flex flex-wrap justify-content-between gap-3 text-muted small"><span>Online learning</span><span>Weekly live sessions</span><span>Certificate track</span><span>Student support</span><span>Career-focused learning</span></div></section>
<section class="py-5"><div class="container"><h2>Featured Courses</h2><div class="row g-4 mt-1"><?php foreach($courses as $c): ?><div class="col-md-6 col-lg-4"><div class="card h-100 shadow-sm"><img src="<?= e($c['thumbnail'] ?: '/assets/images/course-default.svg') ?>" class="card-img-top" alt="course"><div class="card-body"><h5><?= e($c['title']) ?></h5><p><?= e($c['short_description']) ?></p><p class="small text-muted mb-1"><?= e($c['duration']) ?> • <?= e($c['level']) ?></p><p class="fw-semibold mb-3">₹<?= e($c['discounted_price'] ?: $c['price']) ?></p><a href="/course.php?slug=<?= e($c['slug']) ?>" class="btn btn-outline-primary btn-sm">View Details</a></div></div></div><?php endforeach; ?></div></div></section>
<section class="py-5 bg-light"><div class="container"><h2>How It Works</h2><ol class="row g-3 mt-2"><?php foreach(['Register','Enroll & pay','Access dashboard','Attend live/recorded classes','Attempt quizzes','Complete course','Get certificate','Verify certificate online'] as $s): ?><li class="col-md-6"><?= e($s) ?></li><?php endforeach; ?></ol></div></section>
<section class="py-5"><div class="container"><h2>Frequently Asked Questions</h2><div class="accordion" id="faqs"><?php foreach($faqs as $i=>$f): ?><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button <?= $i?'collapsed':'' ?>" data-bs-toggle="collapse" data-bs-target="#f<?= $i ?>"><?= e($f['question']) ?></button></h2><div id="f<?= $i ?>" class="accordion-collapse collapse <?= !$i?'show':'' ?>"><div class="accordion-body"><?= e($f['answer']) ?></div></div></div><?php endforeach; ?></div></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
