<?php $metaTitle='Student Register'; include __DIR__.'/includes/header.php';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!verify_csrf($_POST['csrf_token']??'')) die('Invalid CSRF');
if($_POST['password']!==$_POST['confirm_password']){flash('error','Passwords do not match'); redirect('/register.php');}
$photoPath=null; if(validate_upload($_FILES['profile_photo']??[],['image/jpeg','image/png'])){$name='p_'.time().'_'.basename($_FILES['profile_photo']['name']);move_uploaded_file($_FILES['profile_photo']['tmp_name'],__DIR__.'/assets/uploads/profile/'.$name);$photoPath='/assets/uploads/profile/'.$name;}
try{$stmt=$db->prepare('INSERT INTO students(full_name,email,mobile,password_hash,law_college,year_semester,city_state,profession,profile_photo,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,"active",NOW())');
$stmt->execute([sanitize($_POST['full_name']),sanitize($_POST['email']),sanitize($_POST['mobile']),password_hash($_POST['password'],PASSWORD_DEFAULT),sanitize($_POST['law_college']),sanitize($_POST['year_semester']),sanitize($_POST['city_state']),sanitize($_POST['profession']),$photoPath]);flash('success','Registration successful. Please login.');redirect('/login.php');}
catch(PDOException $e){flash('error','Email already registered.');redirect('/register.php');}}
?>
<section class="container py-5"><h1>Create Student Account</h1><?php if($m=flash('error')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif; ?><form method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>"><div class="col-md-6"><input required name="full_name" class="form-control" placeholder="Full Name"></div><div class="col-md-6"><input required type="email" name="email" class="form-control" placeholder="Email"></div><div class="col-md-6"><input required name="mobile" class="form-control" placeholder="Mobile"></div><div class="col-md-6"><input required name="law_college" class="form-control" placeholder="Law College / University"></div><div class="col-md-6"><input required name="year_semester" class="form-control" placeholder="Year / Semester"></div><div class="col-md-6"><input required name="city_state" class="form-control" placeholder="City / State"></div><div class="col-md-6"><select name="profession" class="form-select"><option>Student</option><option>Advocate</option><option>Associate</option><option>Researcher</option><option>Other</option></select></div><div class="col-md-6"><input type="file" name="profile_photo" accept="image/*" class="form-control"></div><div class="col-md-6"><input required type="password" name="password" class="form-control" placeholder="Password"></div><div class="col-md-6"><input required type="password" name="confirm_password" class="form-control" placeholder="Confirm Password"></div><div class="col-12"><button class="btn btn-primary">Register</button></div></form></section>
<?php include __DIR__.'/includes/footer.php'; ?>
